name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: Setup dependencies
        run: sudo apt-get install -y libmagic-dev librdkafka-dev
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Checkout downloader
        uses: actions/checkout@v2
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: make check

